version: '3'
services:
  web:
    build: site
    container_name: apache-sdk
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: mysql-sdk
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: databaseSdk
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-sdk
    depends_on:
      - database
    ports:
      - 8890:80
    environment:
      - PMA_ARBITRARY=1
