/404:
  controller: "LoginController"
  action: 'handleSuccess'

/handle-failure:
  controller: "LoginController"
  action: 'handleFailure'

/login:
  controller: "LoginController"
  action: 'login'

/redirect_google:
  controller: "LoginController"
  action: 'getCode'

/redirect_facebook:
  controller: "LoginController"
  action: 'handleSuccess'